export const DETAILS = {
  'power-protein': {
    tag: 'Breakfast',
    rating: '4.8/5 (+220 reviews)',
    title: ['Scrambled Eggs with Turkey Bacon and', 'Sautéed Spinach'],
    about: [
      'This nutritious breakfast combines high-quality protein and healthy fats',
      'to fuel your day. The scrambled eggs provide essential amino acids,',
      'while the turkey bacon adds a lean source of protein. Sautéed spinach',
      'contributes vitamins and minerals, making this dish both satisfying and',
      'health-conscious.',
    ],
    img: '/img/dm-hero.jpg',
    info: [
      ['fork', 'Eat Time', '8:00 AM'],
      ['pen', 'Prep Time', '5 minutes'],
      ['pot', 'Cook Time', '10 minutes'],
      ['level', 'Difficulty', 'Easy'],
      ['listnum', 'Total Steps', '4 steps'],
      ['heartcheck', 'Health Score', '85/100'],
    ],
    macros: [
      ['Calories', 350, 'cal'],
      ['Protein', 25, 'gr'],
      ['Carbs', 10, 'gr'],
      ['Fats', 20, 'gr'],
    ],
    ingredients: ['2 large eggs', '2 slices of turkey bacon', '1 cup fresh spinach', '1 tablespoon olive oil', 'Salt and pepper to taste'],
    steps: [
      ['Prep the Ingredients', ['Crack the eggs into a mixing bowl, add a pinch of salt and pepper, and whisk until', 'fully blended.']],
      ['Cook the Turkey Bacon', ['Heat the skillet over medium heat and cook the turkey bacon until crispy, about', '3-4 minutes on each side. Remove and set aside.']],
      ['Sauté the Spinach', ['In the same skillet, add olive oil and spinach. Sauté until the spinach is wilted,', 'about 2-3 minutes. Remove and set aside.']],
      ['Scramble the Eggs', ['Pour the egg mixture into the skillet and cook, stirring gently with a spatula, until', 'the eggs are fully cooked but still soft, about 2-3 minutes.']],
      ['Assemble and Serve', ['Plate the scrambled eggs with turkey bacon and sautéed spinach. Serve', 'immediately.']],
    ],
    tools: ['Non-stick skillet', 'Spatula', 'Mixing bowl', 'Fork', 'Measuring spoons'],
    notes: [
      ['For a lower-calorie option,', 'substitute olive oil with a cooking', 'spray and reduce the amount of', 'turkey bacon.'],
      ['Add a sprinkle of cheese or herbs', 'like chives or parsley for extra', 'flavor.'],
    ],
    nutrition: [
      ['Total Carbohydrates', '10 gr', 1],
      ['Dietary Fiber', '2 gr', 0],
      ['Sugars', '1 gr', 0],
      ['Protein', '25 gr', 1],
      ['Total Fat', '20 gr', 1],
      ['Saturated Fat', '5 gr', 0],
      ['Trans Fat', '0 gr', 0],
      ['Cholesterol', '370 mg', 1],
      ['Sodium', '720 mg', 1],
      ['Potassium', '500 mg', 1],
      ['Vitamin A', '120% DV', 1],
      ['Vitamin C', '20% DV', 1],
      ['Calcium', '10% DV', 1],
      ['Iron', '15% DV', 1],
    ],
    reviews: [
      ['Samantha Lee', '5/5', '/img/rv-samantha.jpg', ['My go-to breakfast is quick, filling, and', 'customizable. I love the fresh taste of', 'spinach, and it’s easy to add other', 'veggies or spices!']],
      ['David Chen', '4.7/5', '/img/rv-david.jpg', ['Delicious and healthy. I sometimes add', 'mushrooms for extra veggies. The', 'turkey bacon is a nice, lean alternative', 'to regular bacon.']],
      ['Jessica Moore', '4.9/5', '/img/rv-jessica.jpg', ['Perfect way to start the day! The', 'combination of eggs, spinach, and', 'turkey bacon is both tasty and', 'nutritious. Highly recommend!']],
    ],
  },
  'lean-and-green': {
    tag: 'Dinner',
    rating: '4.9/5 (+310 reviews)',
    title: ['Baked Salmon with Steamed Broccoli', 'and Brown Rice'],
    about: [
      'A balanced dinner built around omega-3 rich salmon, fibre-packed brown',
      'rice and crisp steamed broccoli. It keeps you full without feeling heavy,',
      'supports muscle recovery after evening training and delivers a steady',
      'release of energy, making it an easy weeknight favourite that still feels',
      'special.',
    ],
    img: '/img/mp-lean.jpg',
    info: [
      ['fork', 'Eat Time', '7:00 PM'],
      ['pen', 'Prep Time', '10 minutes'],
      ['pot', 'Cook Time', '20 minutes'],
      ['level', 'Difficulty', 'Easy'],
      ['listnum', 'Total Steps', '5 steps'],
      ['heartcheck', 'Health Score', '85/100'],
    ],
    macros: [
      ['Calories', 450, 'cal'],
      ['Protein', 35, 'gr'],
      ['Carbs', 40, 'gr'],
      ['Fats', 15, 'gr'],
    ],
    ingredients: ['1 salmon fillet', '1 cup broccoli florets', '1/2 cup brown rice', '1 teaspoon olive oil', 'Lemon, salt and pepper'],
    steps: [
      ['Cook the Rice', ['Rinse the brown rice and simmer it in salted water for about 18 minutes,', 'then cover and let it rest.']],
      ['Season the Salmon', ['Brush the fillet with olive oil, then season with lemon zest, salt and', 'freshly ground pepper.']],
      ['Bake the Salmon', ['Bake at 200°C for 12-14 minutes, until the flesh flakes easily with', 'a fork.']],
      ['Steam the Broccoli', ['Steam the florets for 4-5 minutes so they stay bright green and', 'slightly crisp.']],
      ['Plate and Serve', ['Serve the salmon over the rice with broccoli on the side and a squeeze', 'of lemon.']],
    ],
    tools: ['Baking tray', 'Saucepan', 'Steamer basket', 'Pastry brush', 'Fish spatula'],
    notes: [
      ['Swap the rice for quinoa to', 'raise the protein and lower the', 'glycemic load.'],
      ['Leftover salmon keeps well', 'for lunch the next day.'],
    ],
    nutrition: [
      ['Total Carbohydrates', '40 gr', 1],
      ['Dietary Fiber', '6 gr', 0],
      ['Sugars', '3 gr', 0],
      ['Protein', '35 gr', 1],
      ['Total Fat', '15 gr', 1],
      ['Saturated Fat', '3 gr', 0],
      ['Trans Fat', '0 gr', 0],
      ['Cholesterol', '80 mg', 1],
      ['Sodium', '410 mg', 1],
      ['Potassium', '890 mg', 1],
      ['Vitamin A', '25% DV', 1],
      ['Vitamin C', '140% DV', 1],
      ['Calcium', '8% DV', 1],
      ['Iron', '12% DV', 1],
    ],
  },
  'vegan-energy-boost': {
    tag: 'Lunch',
    rating: '4.7/5 (+185 reviews)',
    title: ['Chickpea and Avocado Salad with', 'Lemon Tahini Dressing'],
    about: [
      'Plant protein from chickpeas meets creamy avocado and a bright lemon',
      'tahini dressing. Packed with fibre, healthy fats and slow carbs, it keeps',
      'energy steady through the afternoon and is ready in under twenty',
      'minutes, which makes it ideal for busy training days and meal prep',
      'boxes.',
    ],
    img: '/img/mp-vegan.jpg',
    info: [
      ['fork', 'Eat Time', '12:30 PM'],
      ['pen', 'Prep Time', '15 minutes'],
      ['pot', 'Cook Time', '5 minutes'],
      ['level', 'Difficulty', 'Medium'],
      ['listnum', 'Total Steps', '4 steps'],
      ['heartcheck', 'Health Score', '80/100'],
    ],
    macros: [
      ['Calories', 400, 'cal'],
      ['Protein', 15, 'gr'],
      ['Carbs', 45, 'gr'],
      ['Fats', 18, 'gr'],
    ],
    ingredients: ['1 cup chickpeas', '1 ripe avocado', '1 cup mixed greens', '2 tablespoons tahini', 'Juice of 1 lemon'],
    steps: [
      ['Rinse the Chickpeas', ['Drain and rinse the chickpeas, then pat them dry with a clean', 'kitchen towel.']],
      ['Make the Dressing', ['Whisk tahini, lemon juice, a splash of water and a pinch of salt until', 'smooth and pourable.']],
      ['Slice the Avocado', ['Halve the avocado, remove the stone and slice it into thin wedges.', '']],
      ['Toss and Serve', ['Toss greens and chickpeas with the dressing, top with avocado and', 'serve right away.']],
      ['Add Toppings', ['Finish with toasted seeds or chilli flakes if you like a little extra', 'crunch.']],
    ],
    tools: ['Mixing bowl', 'Whisk', 'Chef’s knife', 'Cutting board', 'Salad tongs'],
    notes: [
      ['Roast the chickpeas for extra', 'crunch and a smoky flavour.'],
      ['Keep the dressing separate if', 'you are packing it for later.'],
    ],
    nutrition: [
      ['Total Carbohydrates', '45 gr', 1],
      ['Dietary Fiber', '14 gr', 0],
      ['Sugars', '5 gr', 0],
      ['Protein', '15 gr', 1],
      ['Total Fat', '18 gr', 1],
      ['Saturated Fat', '2 gr', 0],
      ['Trans Fat', '0 gr', 0],
      ['Cholesterol', '0 mg', 1],
      ['Sodium', '380 mg', 1],
      ['Potassium', '960 mg', 1],
      ['Vitamin A', '35% DV', 1],
      ['Vitamin C', '45% DV', 1],
      ['Calcium', '12% DV', 1],
      ['Iron', '25% DV', 1],
    ],
  },
  'mediterranean-delight': {
    tag: 'Dinner',
    rating: '4.8/5 (+142 reviews)',
    title: ['Grilled Chicken with Quinoa', 'Tabbouleh and Hummus'],
    about: [
      'Lean grilled chicken over a herby quinoa tabbouleh with a spoon of',
      'smooth hummus. It is high in protein, rich in fibre and full of fresh',
      'Mediterranean flavour, and it reheats well, which makes it a reliable',
      'dinner after strength sessions or a quick lunch the following',
      'day.',
    ],
    img: '/img/mp-med.jpg',
    info: [
      ['fork', 'Eat Time', '7:30 PM'],
      ['pen', 'Prep Time', '15 minutes'],
      ['pot', 'Cook Time', '20 minutes'],
      ['level', 'Difficulty', 'Medium'],
      ['listnum', 'Total Steps', '5 steps'],
      ['heartcheck', 'Health Score', '85/100'],
    ],
    macros: [
      ['Calories', 500, 'cal'],
      ['Protein', 35, 'gr'],
      ['Carbs', 50, 'gr'],
      ['Fats', 18, 'gr'],
    ],
    ingredients: ['1 chicken breast', '1/2 cup quinoa', 'Cucumber and tomato', 'Fresh parsley and mint', '2 tablespoons hummus'],
    steps: [
      ['Cook the Quinoa', ['Simmer the quinoa for 12-15 minutes, then fluff it with a fork and let it', 'cool slightly.']],
      ['Grill the Chicken', ['Season the chicken and grill it for 6-7 minutes per side until it reaches', '75°C inside.']],
      ['Chop the Vegetables', ['Dice cucumber and tomato, and finely chop the parsley and mint.', '']],
      ['Mix the Tabbouleh', ['Combine quinoa, vegetables and herbs with lemon juice and a drizzle', 'of olive oil.']],
      ['Slice and Serve', ['Slice the chicken, serve over the tabbouleh and add hummus on the', 'side.']],
    ],
    tools: ['Grill pan', 'Saucepan', 'Chef’s knife', 'Cutting board', 'Meat thermometer'],
    notes: [
      ['Marinate the chicken overnight', 'in yogurt and lemon for extra', 'tenderness.'],
      ['Use couscous for a quicker', 'version.'],
    ],
    nutrition: [
      ['Total Carbohydrates', '50 gr', 1],
      ['Dietary Fiber', '8 gr', 0],
      ['Sugars', '4 gr', 0],
      ['Protein', '35 gr', 1],
      ['Total Fat', '18 gr', 1],
      ['Saturated Fat', '3 gr', 0],
      ['Trans Fat', '0 gr', 0],
      ['Cholesterol', '95 mg', 1],
      ['Sodium', '520 mg', 1],
      ['Potassium', '720 mg', 1],
      ['Vitamin A', '30% DV', 1],
      ['Vitamin C', '60% DV', 1],
      ['Calcium', '9% DV', 1],
      ['Iron', '22% DV', 1],
    ],
  },
}
